import Head from 'next/head'
import Image from 'next/image'
import Matrix from '../components/Canvas/Sandbox/Matrix'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="container"><div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles["text-area"]}>
          <h1 className={styles.title}>
            Home
          </h1>
          <p className={styles.description}>
            Welcome to Dare Sandbox, experimentation and showcasing environment for projects of all kinds.
          </p>
          <h2 className={styles.title}>Todos</h2>
          <p>
            Some of the projects are finished, some are ongoing. They need to be migrated onto this page and kept in seperate showcase spaces.
          </p>
          <h4 className={styles.title}>
              Component Library
          </h4>
          <p>
            Here are the demonstrations of the React.js components, adapted to the framework by myself. All of them are, as of today, in typescript. Written strictly and working without any flaws.
          </p>
          <h4 className={styles.title}>
            2D Game Engine, Rendering Contexts
          </h4>
          <p>
            Section created to demonstrate the games that are written in the vanilla js game engine that is being developed. It is totally a side hobby and a passion. However, they are developed without production in mind. So take it with a grain of salt...
          </p>
          <h4 className={styles.title}>
            Website Themes
          </h4>
          <p>
            Developing multiple website themes in order to quickly bootstrap for clients.
          </p>
        </div>
        <div className={styles["matrix-wrapper"]}>
          <Matrix />  
        </div>
      </main>
    </div></div>
  )
}
